In [24]:
import pandas as pd 
import numpy as np

In [25]:
df = pd.read_csv('customer.csv')
df = df.iloc[:,2:]

In [28]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size = 0.2)

In [29]:
X_train

     review education
7      Poor    School
37  Average        PG
6      Good    School
24  Average        PG
11     Good        UG
26     Poor        PG
1      Poor        UG
41     Good        PG
8   Average        UG
31     Poor    School
10     Good        UG
34  Average    School
17     Poor        UG
0   Average    School
14     Poor        PG
12     Poor    School
5   Average    School
25     Good    School
48     Good        UG
32  Average        UG
3      Good        PG
27     Poor        PG
33     Good        PG
4   Average        UG
2      Good        PG
29  Average        UG
38     Good    School
44  Average        UG
45     Poor        PG
40     Good    School
21  Average        PG
18     Good    School
20  Average    School
9      Good        UG
22     Poor        PG
43     Poor        PG
36     Good        UG
42     Good        PG
39     Poor        PG
19     Poor        PG

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [80]:
oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

X_train_e = oe.transform(X_train)
X_test_e = oe.transform(X_test)
X_train_e

X_train_e = pd.DataFrame(X_train_e)
X_train_e

      0    1
0   0.0  0.0
1   1.0  2.0
2   2.0  0.0
3   1.0  2.0
4   2.0  1.0
5   0.0  2.0
6   0.0  1.0
7   2.0  2.0
8   1.0  1.0
9   0.0  0.0
10  2.0  1.0
11  1.0  0.0
12  0.0  1.0
13  1.0  0.0
14  0.0  2.0
15  0.0  0.0
16  1.0  0.0
17  2.0  0.0
18  2.0  1.0
19  1.0  1.0
20  2.0  2.0
21  0.0  2.0
22  2.0  2.0
23  1.0  1.0
24  2.0  2.0
25  1.0  1.0
26  2.0  0.0
27  1.0  1.0
28  0.0  2.0
29  2.0  0.0
30  1.0  2.0
31  2.0  0.0
32  1.0  0.0
33  2.0  1.0
34  0.0  2.0
35  0.0  2.0
36  2.0  1.0
37  2.0  2.0
38  0.0  2.0
39  0.0  2.0

In [104]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y_train)

y_train_label = le.transform(y_train)
y_test_label = le.transform(y_test)


y_train
X_train.head(10)

7     Yes
37    Yes
6      No
24    Yes
11    Yes
26     No
1      No
41    Yes
8      No
31    Yes
10    Yes
34     No
17    Yes
0      No
14    Yes
12     No
5     Yes
25     No
48    Yes
32    Yes
3      No
27     No
33    Yes
4      No
2      No
29    Yes
38     No
44     No
45    Yes
40     No
21     No
18     No
20    Yes
9     Yes
22    Yes
43     No
36    Yes
42    Yes
39     No
19    Yes
Name: purchased, dtype: object